[tools]
python = "3.14"
uv = "latest"

###### Shell aliases ######

[shell_alias]
m = "mise run"
i = "mise run install"
u = "mise run update"
l = "mise run lint"
t = "mise run test"
d = "mise run local-docs"

ll = "ls -l"
la = "ls -a"

g = "git"
gco = "git checkout"
gb = "git branch"
gd = "git diff"
gs = "git status"
ga = "git add"
gc = "git commit"
gp = "git push"


###### Settings ######

[settings]
python.uv_venv_auto = "create|source"

###### Setup ######
[tasks.dev]
description = "Setup the dev environment"
depends = ["precommit", "install"]

[tasks.precommit]
description = "Install pre-commit hooks"
run = "pre-commit autoupdate && pre-commit install"

[tasks.install]
description = "Install dependencies"
alias = "i"
run = "uv sync"


[tasks.update]
description = "Update dependencies"
alias = "u"
run = "uv lock --upgrade"

##### Common Tasks #####

[tasks.lint]
description = "Lint and format code"
alias = "l"
run = "ruff check --fix . && ruff format ."

[tasks.test]
description = "Run tests with coverage"
alias = "t"
run = "coverage run -m pytest . && coverage report -m && coverage xml"

[tasks.all]
description = "Full setup from scratch"
depends = ["install", "lint", "test"]

##### Docs #####

[tasks.install-docs]
description = "Install documentation dependencies"
run = "uv sync --group docs"
hide = true

[tasks.docs]
description = "Build and deploy documentation to GitHub pages"
depends = ["install-docs"]
run = "mkdocs gh-deploy --force"

[tasks.local-docs]
description = "Serve documentation on a local server"
alias = "d"
depends = ["install-docs"]
run = "mkdocs serve"

###### Scripts ######

[tasks.app]
description = "Run the app"
alias = "a"
run = "app"

[tasks.init]
description = "Initialize project (run once)"
alias = "p"
run = "init"

