name: Format, Lint, and Test

on:
  workflow_call:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.14"
          - "3.13"
          - "3.12"
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
        with:
          tool_versions: |
            python ${{ matrix.python-version }}
      - name: Install dependencies
        run: mise run install
      - name: Format and lint
        run: mise run lint
      - name: Run tests
        run: mise run test
