name: Format, Lint, and Test

on:
  workflow_call:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.14"
          - "3.13"
          - "3.12"
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: jdx/mise-action@5083de0e626e95c1c8f1f50a04944d6db8753235 # v4.4.0
        with:
          tool_versions: |
            python ${{ matrix.python-version }}
      - name: Install dependencies
        run: mise run install
      - name: Format and lint
        run: mise run lint
      - name: Run tests
        run: mise run test
